### ISSUE TITLE
No more Fish are spawning

### ISSUE THREAD

**Issue by LostRobinnn** [Cursee-Development/Sleepy-Hollows#1]
### Mod Version

1.20.1

### Latest Version

- [X] Yes, I’m using the latest version.

### Issue Description

When i use this mod no more water mobs are spawning.

### Steps to Reproduce

.

### Logs

.

### Minimal Instance Test

- [X] Yes, I’ve tested it with a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Whoops, sorry! The issue was caused by a non-functional tag: `fluids/water.` I’ll upload the version with the fixed error later.

**Comment by satisfyu** [comment]
This should be fixed and uploaded. 

https://www.curseforge.com/minecraft/mc-mods/sleepy-hollows/files/all?page=1&pageSize=20
