### ISSUE TITLE
Hauntbound armor is insanely fragile

### ISSUE THREAD

**Issue by Yolo1324** [Cursee-Development/Sleepy-Hollows#6]
### Mod Version

1.0.2

### Latest Version

- [X] Yes, I’m using the latest version.

### Issue Description

The Hauntbound armor set has less than 20 durability points each, simple as that. Unless I'm missing something and those are the intended values for reasons I'm yet to find out.

### Steps to Reproduce

Just equip a full set with F3+H on, take damage from any source that affects armor durability and see for yourself

### Minimal Instance Test

- [ ] Yes, I’ve tested it with a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
You can fully configurate it by using the config.

**Comment by satisfyu** [comment]
I'm going to close this as not planned. You're able to fully configurate all Armor Values (Defense, Durability, etc.) by using the config files.
